// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoTRRfdPnmn1hZ2gtyyHVoJH-fB9ycj2U',
    appId: '1:804608414694:web:ee018488836ba5160a7c27',
    messagingSenderId: '804608414694',
    projectId: 'testapp2-2f6f3',
    authDomain: 'testapp2-2f6f3.firebaseapp.com',
    storageBucket: 'testapp2-2f6f3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOtr0VwXfNn8lIuPKsXl2EKGbmUXciuMk',
    appId: '1:804608414694:android:ffef70018f2a342a0a7c27',
    messagingSenderId: '804608414694',
    projectId: 'testapp2-2f6f3',
    storageBucket: 'testapp2-2f6f3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALNlMSM4FYoiaW6hxeDdVglz-OMf71TEM',
    appId: '1:804608414694:ios:4fe3a3c0a1f91c120a7c27',
    messagingSenderId: '804608414694',
    projectId: 'testapp2-2f6f3',
    storageBucket: 'testapp2-2f6f3.firebasestorage.app',
    iosBundleId: 'com.example.assignment1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALNlMSM4FYoiaW6hxeDdVglz-OMf71TEM',
    appId: '1:804608414694:ios:4fe3a3c0a1f91c120a7c27',
    messagingSenderId: '804608414694',
    projectId: 'testapp2-2f6f3',
    storageBucket: 'testapp2-2f6f3.firebasestorage.app',
    iosBundleId: 'com.example.assignment1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAoTRRfdPnmn1hZ2gtyyHVoJH-fB9ycj2U',
    appId: '1:804608414694:web:43cc2b335a278dab0a7c27',
    messagingSenderId: '804608414694',
    projectId: 'testapp2-2f6f3',
    authDomain: 'testapp2-2f6f3.firebaseapp.com',
    storageBucket: 'testapp2-2f6f3.firebasestorage.app',
  );
}
